### PR TITLE
issue/20: added firebug and mobile iframe buttons

### PR DESCRIPTION
**Pull request by oliverfoster**
* added firebug button which only shows on mobile, doesn't load firebug until you hit the button
* added iframe force size and iframe force resize event
* added iframe test page

### CODE REVIEW

**Comment by moloko** [comment]
slight issue when you go to open FB for the first time in that it appears above the drawer then immediately disappears. Works fine after that though.

ezgif-5-95e52a8a71

Be useful to have a bit more information about the iframe force size and iframe force resize functionality

**Comment by oliverfoster** [comment]
Chris and I aren't sure if this will go into devtools as it's pretty hacky, unsupported and a bit heavy to distribute. What do you think?

**Comment by moloko** [comment]
well from the size aspect it's 674KB but as far as I can see won't actually be downloaded until you click the button... if that's right then I don't think there's any concern there.

I think it really comes down to whether it will actually be useful or not.

**Comment by oliverfoster** [comment]
My view is that it'll only be useful inside an App environment where there is no other choice. For that matter I wouldn't be against making this a separate extension as it is very much an edge case thing.

The two buttons were useful for my tests with the Moodle App but I'm not sure they're relevant in evey case:
* iframe force size - Finds the iframe in its parent and resizes it according to the `window.innerHeight` and `window.innerWidth` of its global context (`window.top` from inside the content).
* iframe force resize - Triggers a resize event on the `window.top` to test if any app code is attached to that event.

**Comment by moloko** [comment]
separate extension sounds good to me

**Pull request closed without merging**
