### PR TITLE
issue/59 Show all alt text

### LINKED ISSUE #59: Show all alt text not just images

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #59 

Code needs to be made compatible with fw v5 or devtools needs updating to es6

alttext

### CODE REVIEW

**Comment by kirsty-hames** [comment]
This is great thank you @oliverfoster. I've only tested in a fresh FW instance but I'll see how it behaves in some existing projects too. The only aria label I can see missing is the navigation PLP button. Not sure why as this uses the same `aria-label`  class used elsewhere....

**Review by kirsty-hames — APPROVED** [review]
Works well dropped into projects. Really useful tool!

**Comment by oliverfoster** [comment]
Fixed @kirsty-hames

**Comment by kirsty-hames** [comment]
The height of the annotation button is relative to the annotation text size. In instances where the annotation text is lengthy, the button height is very big.
devtools_button_size_closed  devtools_button_size


Setting `align-items: flex-start` on the `.devtools__annotation-order` prevents this from happening.

**Comment by oliverfoster** [comment]
@chris-steele is this compatible with v5 of the fw? I didn't check but I did try to write the code without using ES6

**Comment by kirsty-hames** [comment]
> @chris-steele is this compatible with v5 of the fw? I didn't check but I did try to write the code without using ES6
> 
> https://github.com/cgkineo/adapt-devtools/blob/b65b4996872d20bf9d62e86c07187b1138a8cd0a/bower.json#L8

I've installed this in a build running v5.19.4 FW and had no problems.

**Comment by oliverfoster** [comment]
> > @chris-steele is this compatible with v5 of the fw? I didn't check but I did try to write the code without using ES6
> > https://github.com/cgkineo/adapt-devtools/blob/b65b4996872d20bf9d62e86c07187b1138a8cd0a/bower.json#L8
> 
> I've installed this in a build running v5.19.4 FW and had no problems.

You'd need to install v5.0.0 to test. It didn't have ES6 transpiling in it and devtools supports from >=v5.0.0

**Pull request merged**
